package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.Arf;
import com.xtt.common.dao.po.ArfPO;

@Repository
public interface ArfMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insert(Arf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insertSelective(Arf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	Arf selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKeySelective(Arf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table arf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKey(Arf record);

	/**
	 * 根据透析活动ID查询最新历史记录
	 * 
	 * @Title: selectByDCId
	 * @param dcId
	 *            透析活动ID
	 * @return MedicalHistory
	 * 
	 */
	Arf selectByDCId(Long dcId);

	/**
	 * 根据透析活动ID取得信息
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return Arf
	 * 
	 */
	Arf selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<ArfPO>
	 * 
	 */
	List<ArfPO> selectByPatientId(Long patientId);
}