package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.AssayReportFilterRule;

@Repository
public interface AssayReportFilterRuleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    int insert(AssayReportFilterRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    int insertSelective(AssayReportFilterRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    AssayReportFilterRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    int updateByPrimaryKeySelective(AssayReportFilterRule record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_filter_rule
     * 
     * @mbggenerated Tue May 24 19:36:27 CST 2016
     */
    int updateByPrimaryKey(AssayReportFilterRule record);

    // 自定义
    /**
     * 查询所有的过滤规则
     * 
     * @Title: selectAll
     * @return
     * 
     */
    List<AssayReportFilterRule> selectAll(AssayReportFilterRule record);
}