package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.Crf;
import com.xtt.common.dao.po.CrfPO;

@Repository
public interface CrfMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insert(Crf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insertSelective(Crf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	Crf selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKeySelective(Crf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKey(Crf record);

	/**
	 * 根据透析活动ID查询最新历史记录
	 * 
	 * @Title: selectByDCId
	 * @param dcId
	 *            透析活动ID
	 * @return Crf
	 * 
	 */
	Crf selectByDCId(Long dcId);

	/**
	 * 根据透析活动ID查询最新历史记录
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return Crf
	 * 
	 */
	Crf selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<CrfPO>
	 * 
	 */
	List<CrfPO> selectByPatientId(Long patientId);
}