package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.MedicalHistory;
import com.xtt.common.dao.po.MedicalHistoryPO;

@Repository
public interface MedicalHistoryMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	int insert(MedicalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	int insertSelective(MedicalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	MedicalHistory selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	int updateByPrimaryKeySelective(MedicalHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table medical_history
	 * 
	 * @mbggenerated Wed Sep 09 15:47:25 CST 2015
	 */
	int updateByPrimaryKey(MedicalHistory record);

	/**
	 * 根据透析活动ID查询最新历史记录
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return MedicalHistory
	 * 
	 */
	MedicalHistoryPO selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<SeriousCrfPO>
	 * 
	 */
	List<MedicalHistoryPO> selectByPatientId(Long patientId);

	/**
	 * 获取最新病史询问数据
	 * 
	 * @Title: selectLastestByPatientId
	 * @param patientId
	 * @return
	 * 
	 */
	MedicalHistory selectLastestByPatientId(Long patientId);
}