package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.OtherDiagnosisResult;
import com.xtt.common.dao.po.OtherDiagnosisResultPO;

@Repository
public interface OtherDiagnosisResultMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insert(OtherDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insertSelective(OtherDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	OtherDiagnosisResult selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKeySelective(OtherDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table other_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKey(OtherDiagnosisResult record);

	/**
	 * 根据透析活动ID取得信息
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return OtherDiagnosisResult
	 * 
	 */
	OtherDiagnosisResult selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<OtherDiagnosisResultPO>
	 * 
	 */
	List<OtherDiagnosisResultPO> selectByPatientId(Long patientId);
}