package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PathologicDiagnosisResult;
import com.xtt.common.dao.po.PathologicDiagnosisResultPO;

@Repository
public interface PathologicDiagnosisResultMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insert(PathologicDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insertSelective(PathologicDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	PathologicDiagnosisResult selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKeySelective(PathologicDiagnosisResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pathologic_diagnosis_result
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKey(PathologicDiagnosisResult record);

	/**
	 * 根据透析活动ID取得信息
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return PathologicDiagnosisResult
	 * 
	 */
	PathologicDiagnosisResultPO selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<PathologicDiagnosisResultPO>
	 * 
	 */
	List<PathologicDiagnosisResultPO> selectByPatientId(Long patientId);
}