package com.xtt.common.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PatientAssayClass;
import com.xtt.common.dao.po.PatientAssayClassPO;

@Repository
public interface PatientAssayClassMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    int insert(PatientAssayClass record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    int insertSelective(PatientAssayClass record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    PatientAssayClass selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(PatientAssayClass record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_class
     * 
     * @mbggenerated Tue Jun 21 20:02:13 CST 2016
     */
    int updateByPrimaryKey(PatientAssayClass record);

    /**
     * 查询所有
     */
    List<PatientAssayClassPO> selectAllByAssayClass(PatientAssayClass record);

    /**
     * 查询所有病患化验类的GroupName
     */
    List<PatientAssayClassPO> selectAllGroupName(PatientAssayClass record);

    /**
     * 删除表中所有数据
     */
    void deleteAllByAssayClass(PatientAssayClass record);

    /**
     * 通过patientAssayMonthRScope的月份来查询
     */
    List<PatientAssayClassPO> selectByMonth(@Param(value = "month") Integer month, @Param(value = "fkTenantId") Integer fkTenantId);

    List<PatientAssayClassPO> selectAllByCondiction(PatientAssayClass record);

}