package com.xtt.common.dao.mapper;

import com.xtt.common.dao.model.PatientDiagnosis;

public interface PatientDiagnosisMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	int insert(PatientDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	int insertSelective(PatientDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	PatientDiagnosis selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	int updateByPrimaryKeySelective(PatientDiagnosis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_diagnosis
	 *
	 * @mbggenerated Tue Jun 28 19:32:55 CST 2016
	 */
	int updateByPrimaryKey(PatientDiagnosis record);
}