package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PatientCard;
import com.xtt.common.dao.po.PatientCardPO;

@Repository
public interface PatientCardMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	int insert(PatientCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	int insertSelective(PatientCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	PatientCard selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	int updateByPrimaryKeySelective(PatientCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_card
	 *
	 * @mbggenerated Tue May 17 10:25:21 CST 2016
	 */
	int updateByPrimaryKey(PatientCard record);

	/**
	 * 自定义
	 * 
	 * @param cardNo
	 * @return
	 */
	List<PatientCardPO> selectByCardNo(PatientCardPO record);

	int deleteByPatientCardPO(PatientCardPO record);
}