package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PatientOrders;
import com.xtt.common.dao.po.PatientOrdersPO;

@Repository
public interface PatientOrdersMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    int insert(PatientOrders record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    int insertSelective(PatientOrders record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    PatientOrders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    int updateByPrimaryKeySelective(PatientOrders record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_orders
     *
     * @mbggenerated Sun Jun 12 15:54:04 CST 2016
     */
    int updateByPrimaryKey(PatientOrders record);

    // 自定义
    List<PatientOrders> selectByPatientOrdersPO(PatientOrders pto);

    /**
     * 根据条件查询his医嘱
     * 
     * @Title: selectByCondition
     * @param record
     * @return
     *
     */
    List<PatientOrders> selectByCondition(PatientOrders record);

    // 下载医嘱信息
    List<PatientOrdersPO> selectDownOrdersPO(PatientOrdersPO orders);

    /**
     * 获取患者对应的项目名称
     * 
     * @param orders
     * @return
     */
    List<PatientOrdersPO> listItemNames(PatientOrdersPO orders);

    /**
     * 获取患者对应的项目名称
     *
     * @param orders
     * @return
     */
    List<PatientOrdersPO> listPatientOrdersPO(PatientOrdersPO orders);
}
