package com.xtt.common.dao.mapper;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PatientHistory;

@Repository
public interface PatientHistoryMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_history
	 * 
	 * @mbggenerated Fri Nov 13 11:23:23 CST 2015
	 */
	int insert(PatientHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table patient_history
	 * 
	 * @mbggenerated Fri Nov 13 11:23:23 CST 2015
	 */
	int insertSelective(PatientHistory record);
}