package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.PatientAssayDictionary;
import com.xtt.common.dao.po.PatientAssayDictionaryPO;

@Repository
public interface PatientAssayDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    int insert(PatientAssayDictionary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    int insertSelective(PatientAssayDictionary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    PatientAssayDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    int updateByPrimaryKeySelective(PatientAssayDictionary record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table patient_assay_dictionary
     *
     * @mbggenerated Wed Jan 27 20:16:53 CST 2016
     */
    int updateByPrimaryKey(PatientAssayDictionary record);

    /* 自定义 */
    /**
     * 根据条件查询类别数据
     * 
     * @Title: selectByCondition
     * @param record
     * @return
     *
     */
    List<PatientAssayDictionaryPO> selectByCondition(PatientAssayDictionary record);

    /**
     * 根据字典模糊查询数据
     * 
     * @Title: selectByCondition
     * @param record
     * @return
     *
     */
    List<PatientAssayDictionaryPO> selectByFuzzyCondition(PatientAssayDictionary record);

}