package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.Province;

@Repository
public interface ProvinceMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	int insert(Province record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	int insertSelective(Province record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	Province selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	int updateByPrimaryKeySelective(Province record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province
	 * 
	 * @mbggenerated Wed Sep 16 11:45:16 CST 2015
	 */
	int updateByPrimaryKey(Province record);

	List<Province> selectProvinceList();
}