package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SeriousCrf;
import com.xtt.common.dao.po.SeriousCrfPO;

@Repository
public interface SeriousCrfMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insert(SeriousCrf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int insertSelective(SeriousCrf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	SeriousCrf selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKeySelective(SeriousCrf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table serious_crf
	 * 
	 * @mbggenerated Tue Sep 08 13:30:46 CST 2015
	 */
	int updateByPrimaryKey(SeriousCrf record);

	/**
	 * 根据透析活动ID查询最新历史记录
	 * 
	 * @Title: selectByDCId
	 * @param dcId
	 *            透析活动ID
	 * @return SeriousCrf
	 * 
	 */
	SeriousCrf selectByDCId(Long dcId);

	/**
	 * 根据透析活动ID取得信息
	 * 
	 * @Title: selectByDCId
	 * @param pdId
	 *            患者诊断主表ID
	 * @return SeriousCrf
	 * 
	 */
	SeriousCrf selectByPDId(Long pdId);

	/**
	 * 根据患者ID查询历史记录
	 * 
	 * @Title: selectByPatientId
	 * @param patientId
	 *            患者ID
	 * @return List<SeriousCrfPO>
	 * 
	 */
	List<SeriousCrfPO> selectByPatientId(Long patientId);
}