package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SysLog;

@Repository
public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    SysLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int updateByPrimaryKey(SysLog record);

    List<SysLog> selectSysLog(SysLog record);
}