package com.xtt.common.dao.mapper;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SysRole2obj;

@Repository
public interface SysRole2objMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role2obj
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insert(SysRole2obj record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role2obj
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insertSelective(SysRole2obj record);

    /**
     * 根据roleId删除所有的关联菜单数据
     * 
     * @Title: deleteByRoleId
     * @param roleId
     *
     */
    void deleteByRoleId(Long roleId);

    /**
     * 批量插入数据
     * 
     * @Title: batchInsert
     * @param menus
     *
     */
    void batchInsert(SysRole2obj[] menus);

    /**
     * 根据角色id批量删除对象
     * 
     * @Title: batchDeleteByRoleIds
     * @param roleIds
     *
     */
    void batchDeleteByRoleIds(Long[] roleIds);

    /**
     * 根据菜单id批量删除对象
     * 
     * @Title: deleteByMenuKey
     * @param menuKeys
     *
     */
    void deleteByMenuKey(@Param("menuKeys") String[] menuKeys, @Param("tenantId") Integer tenantId);

    /**
     * 通过角色id和类型删除对象
     * 
     * @Title: deleteByRoleIdAndType
     * @param menuRoleId
     * @param types
     *
     */
    void deleteByRoleIdAndType(@Param("roleId") Long roleId, @Param("types") String[] types);
}