package com.xtt.common.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SysRole;

@Repository
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    SysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
     * 
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    int updateByPrimaryKey(SysRole record);

    /**
     * 通过租户id获取该租户所有角色
     * 
     * @param tenantId
     * 
     * @Title: selectSysRoleByTenantId
     * @return
     * 
     */
    List<SysRole> selectSysRoleByTenantId(@Param("tenantId") int tenantId, @Param("sysOwner") String sysOwner);

    /**
     * 根据roleIds 批量删除角色数据
     * 
     * @Title: batchDeleteByRoleIds
     * @param roleIds
     *
     */
    int batchDeleteByRoleIds(Long[] roleIds);

    /**
     * 批量插入角色数据
     * 
     * @Title: batchInsert
     * @param roles
     *
     */
    void batchInsert(List<SysRole> roles);

    /**
     * 根据固定角色类型查找当前租户下的对象
     * 
     * @Title: selectByConstant
     * @param constantTypes
     * @param tenantId
     * @return
     *
     */
    List<SysRole> selectByConstant(@Param("constantTypes") int[] constantTypes, @Param("tenantId") Integer tenantId,
                    @Param("sysOwner") String sysOwner);
}