package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SysTenant;

@Repository
public interface SysTenantMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	int insert(SysTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	int insertSelective(SysTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	SysTenant selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	int updateByPrimaryKeySelective(SysTenant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	int updateByPrimaryKey(SysTenant record);

	// 自定义

	Long notifyDB();

	List<SysTenant> selectAll();
}