package com.xtt.common.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.xtt.common.dao.model.SysTenant;

@Repository
public interface SysTenantMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    int insert(SysTenant record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    int insertSelective(SysTenant record);

    /**
     * @Title: selectTenantByName
     * @param record
     * @return 校验是否重复添加
     */
    List<SysTenant> selectTenantByName(SysTenant record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    SysTenant selectByPrimaryKey(Integer id);

    /**
     * @Title: selectByName
     * @param name
     * @return 查看某医院的信息
     */
    SysTenant selectByName(String name);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    int updateByPrimaryKeySelective(SysTenant record);

    /**
     * @Title: updateEnable
     * @param sysTenant
     * @return 自动失效
     */
    int updateEnable(SysTenant sysTenant);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table sys_tenant
     * 
     * @mbggenerated Thu Mar 03 13:46:30 CST 2016
     */
    int updateByPrimaryKey(SysTenant record);

    /**
     * @Title: selectAll
     * @return List<SysTenant> 查询所的医院信息
     */
    List<SysTenant> selectAll();

    /**
     * @Title: selectAllSwitch
     * @return 查询所有可用状态下的医院信息
     */
    List<SysTenant> selectAllSwitch();

    /**
     * 根据条件查询默认租户
     * 
     * @Title: selectByCondition
     * @return
     * 
     */
    SysTenant selectDefault(SysTenant record);
}