package com.xtt.common.dao.model;

import java.util.Date;

public class CkdStage {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.fk_patient_diagnosis_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long fkPatientDiagnosisId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.fk_dialysis_campaign_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long fkDialysisCampaignId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.fk_patient_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long fkPatientId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.ckd_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private String ckdType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.ckd_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private String ckdStage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.aki_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private String akiType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.aki_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private String akiStage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.is_draft
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Boolean isDraft;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.operator_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long operatorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.version
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Integer version;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.is_enable
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Boolean isEnable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.create_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.update_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Long updateUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ckd_stage.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	private Integer fkTenantId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.id
	 *
	 * @return the value of ckd_stage.id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.id
	 *
	 * @param id
	 *            the value for ckd_stage.id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.fk_patient_diagnosis_id
	 *
	 * @return the value of ckd_stage.fk_patient_diagnosis_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getFkPatientDiagnosisId() {
		return fkPatientDiagnosisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.fk_patient_diagnosis_id
	 *
	 * @param fkPatientDiagnosisId
	 *            the value for ckd_stage.fk_patient_diagnosis_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setFkPatientDiagnosisId(Long fkPatientDiagnosisId) {
		this.fkPatientDiagnosisId = fkPatientDiagnosisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.fk_dialysis_campaign_id
	 *
	 * @return the value of ckd_stage.fk_dialysis_campaign_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getFkDialysisCampaignId() {
		return fkDialysisCampaignId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.fk_dialysis_campaign_id
	 *
	 * @param fkDialysisCampaignId
	 *            the value for ckd_stage.fk_dialysis_campaign_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setFkDialysisCampaignId(Long fkDialysisCampaignId) {
		this.fkDialysisCampaignId = fkDialysisCampaignId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.fk_patient_id
	 *
	 * @return the value of ckd_stage.fk_patient_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getFkPatientId() {
		return fkPatientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.fk_patient_id
	 *
	 * @param fkPatientId
	 *            the value for ckd_stage.fk_patient_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setFkPatientId(Long fkPatientId) {
		this.fkPatientId = fkPatientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.ckd_type
	 *
	 * @return the value of ckd_stage.ckd_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public String getCkdType() {
		return ckdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.ckd_type
	 *
	 * @param ckdType
	 *            the value for ckd_stage.ckd_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setCkdType(String ckdType) {
		this.ckdType = ckdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.ckd_stage
	 *
	 * @return the value of ckd_stage.ckd_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public String getCkdStage() {
		return ckdStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.ckd_stage
	 *
	 * @param ckdStage
	 *            the value for ckd_stage.ckd_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setCkdStage(String ckdStage) {
		this.ckdStage = ckdStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.aki_type
	 *
	 * @return the value of ckd_stage.aki_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public String getAkiType() {
		return akiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.aki_type
	 *
	 * @param akiType
	 *            the value for ckd_stage.aki_type
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setAkiType(String akiType) {
		this.akiType = akiType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.aki_stage
	 *
	 * @return the value of ckd_stage.aki_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public String getAkiStage() {
		return akiStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.aki_stage
	 *
	 * @param akiStage
	 *            the value for ckd_stage.aki_stage
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setAkiStage(String akiStage) {
		this.akiStage = akiStage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.is_draft
	 *
	 * @return the value of ckd_stage.is_draft
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Boolean getIsDraft() {
		return isDraft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.is_draft
	 *
	 * @param isDraft
	 *            the value for ckd_stage.is_draft
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setIsDraft(Boolean isDraft) {
		this.isDraft = isDraft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.operator_id
	 *
	 * @return the value of ckd_stage.operator_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.operator_id
	 *
	 * @param operatorId
	 *            the value for ckd_stage.operator_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setOperatorId(Long operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.version
	 *
	 * @return the value of ckd_stage.version
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.version
	 *
	 * @param version
	 *            the value for ckd_stage.version
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.is_enable
	 *
	 * @return the value of ckd_stage.is_enable
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Boolean getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.is_enable
	 *
	 * @param isEnable
	 *            the value for ckd_stage.is_enable
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.create_time
	 *
	 * @return the value of ckd_stage.create_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.create_time
	 *
	 * @param createTime
	 *            the value for ckd_stage.create_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.create_user_id
	 *
	 * @return the value of ckd_stage.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.create_user_id
	 *
	 * @param createUserId
	 *            the value for ckd_stage.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.update_time
	 *
	 * @return the value of ckd_stage.update_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.update_time
	 *
	 * @param updateTime
	 *            the value for ckd_stage.update_time
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.update_user_id
	 *
	 * @return the value of ckd_stage.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Long getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.update_user_id
	 *
	 * @param updateUserId
	 *            the value for ckd_stage.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ckd_stage.fk_tenant_id
	 *
	 * @return the value of ckd_stage.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public Integer getFkTenantId() {
		return fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ckd_stage.fk_tenant_id
	 *
	 * @param fkTenantId
	 *            the value for ckd_stage.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 10:30:11 CST 2016
	 */
	public void setFkTenantId(Integer fkTenantId) {
		this.fkTenantId = fkTenantId;
	}
}