package com.xtt.common.dao.model;

import java.util.Date;

public class Crf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long fkPatientDiagnosisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.fk_clinical_diagnosis_result_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long fkClinicalDiagnosisResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long fkPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String sgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherSgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String pgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherPgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String hereditaryNephropathy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherHereditaryNephropathy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String tin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherTin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.urologic_neoplasms
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Boolean urologicNeoplasms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String unAndStone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherUnAndStone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String renalResection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherRenalResection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.unknown_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Boolean unknownReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.other_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private String otherReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.is_draft
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Boolean isDraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.operator_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.version
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.is_enable
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.create_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.create_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.update_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.update_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crf.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.id
     *
     * @return the value of crf.id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.id
     *
     * @param id the value for crf.id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.fk_patient_diagnosis_id
     *
     * @return the value of crf.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getFkPatientDiagnosisId() {
        return fkPatientDiagnosisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.fk_patient_diagnosis_id
     *
     * @param fkPatientDiagnosisId the value for crf.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setFkPatientDiagnosisId(Long fkPatientDiagnosisId) {
        this.fkPatientDiagnosisId = fkPatientDiagnosisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.fk_clinical_diagnosis_result_id
     *
     * @return the value of crf.fk_clinical_diagnosis_result_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getFkClinicalDiagnosisResultId() {
        return fkClinicalDiagnosisResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.fk_clinical_diagnosis_result_id
     *
     * @param fkClinicalDiagnosisResultId the value for crf.fk_clinical_diagnosis_result_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setFkClinicalDiagnosisResultId(Long fkClinicalDiagnosisResultId) {
        this.fkClinicalDiagnosisResultId = fkClinicalDiagnosisResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.fk_patient_id
     *
     * @return the value of crf.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getFkPatientId() {
        return fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.fk_patient_id
     *
     * @param fkPatientId the value for crf.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setFkPatientId(Long fkPatientId) {
        this.fkPatientId = fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.sgn
     *
     * @return the value of crf.sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getSgn() {
        return sgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.sgn
     *
     * @param sgn the value for crf.sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setSgn(String sgn) {
        this.sgn = sgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_sgn
     *
     * @return the value of crf.other_sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherSgn() {
        return otherSgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_sgn
     *
     * @param otherSgn the value for crf.other_sgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherSgn(String otherSgn) {
        this.otherSgn = otherSgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.pgn
     *
     * @return the value of crf.pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getPgn() {
        return pgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.pgn
     *
     * @param pgn the value for crf.pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setPgn(String pgn) {
        this.pgn = pgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_pgn
     *
     * @return the value of crf.other_pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherPgn() {
        return otherPgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_pgn
     *
     * @param otherPgn the value for crf.other_pgn
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherPgn(String otherPgn) {
        this.otherPgn = otherPgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.hereditary_nephropathy
     *
     * @return the value of crf.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getHereditaryNephropathy() {
        return hereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.hereditary_nephropathy
     *
     * @param hereditaryNephropathy the value for crf.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setHereditaryNephropathy(String hereditaryNephropathy) {
        this.hereditaryNephropathy = hereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_hereditary_nephropathy
     *
     * @return the value of crf.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherHereditaryNephropathy() {
        return otherHereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_hereditary_nephropathy
     *
     * @param otherHereditaryNephropathy the value for crf.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherHereditaryNephropathy(String otherHereditaryNephropathy) {
        this.otherHereditaryNephropathy = otherHereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.tin
     *
     * @return the value of crf.tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getTin() {
        return tin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.tin
     *
     * @param tin the value for crf.tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setTin(String tin) {
        this.tin = tin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_tin
     *
     * @return the value of crf.other_tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherTin() {
        return otherTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_tin
     *
     * @param otherTin the value for crf.other_tin
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherTin(String otherTin) {
        this.otherTin = otherTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.urologic_neoplasms
     *
     * @return the value of crf.urologic_neoplasms
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Boolean getUrologicNeoplasms() {
        return urologicNeoplasms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.urologic_neoplasms
     *
     * @param urologicNeoplasms the value for crf.urologic_neoplasms
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setUrologicNeoplasms(Boolean urologicNeoplasms) {
        this.urologicNeoplasms = urologicNeoplasms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.un_and_stone
     *
     * @return the value of crf.un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getUnAndStone() {
        return unAndStone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.un_and_stone
     *
     * @param unAndStone the value for crf.un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setUnAndStone(String unAndStone) {
        this.unAndStone = unAndStone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_un_and_stone
     *
     * @return the value of crf.other_un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherUnAndStone() {
        return otherUnAndStone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_un_and_stone
     *
     * @param otherUnAndStone the value for crf.other_un_and_stone
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherUnAndStone(String otherUnAndStone) {
        this.otherUnAndStone = otherUnAndStone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.renal_resection
     *
     * @return the value of crf.renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getRenalResection() {
        return renalResection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.renal_resection
     *
     * @param renalResection the value for crf.renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setRenalResection(String renalResection) {
        this.renalResection = renalResection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_renal_resection
     *
     * @return the value of crf.other_renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherRenalResection() {
        return otherRenalResection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_renal_resection
     *
     * @param otherRenalResection the value for crf.other_renal_resection
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherRenalResection(String otherRenalResection) {
        this.otherRenalResection = otherRenalResection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.unknown_reason
     *
     * @return the value of crf.unknown_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Boolean getUnknownReason() {
        return unknownReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.unknown_reason
     *
     * @param unknownReason the value for crf.unknown_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setUnknownReason(Boolean unknownReason) {
        this.unknownReason = unknownReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.other_reason
     *
     * @return the value of crf.other_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public String getOtherReason() {
        return otherReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.other_reason
     *
     * @param otherReason the value for crf.other_reason
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOtherReason(String otherReason) {
        this.otherReason = otherReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.is_draft
     *
     * @return the value of crf.is_draft
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Boolean getIsDraft() {
        return isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.is_draft
     *
     * @param isDraft the value for crf.is_draft
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.operator_id
     *
     * @return the value of crf.operator_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.operator_id
     *
     * @param operatorId the value for crf.operator_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.version
     *
     * @return the value of crf.version
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.version
     *
     * @param version the value for crf.version
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.is_enable
     *
     * @return the value of crf.is_enable
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.is_enable
     *
     * @param isEnable the value for crf.is_enable
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.create_time
     *
     * @return the value of crf.create_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.create_time
     *
     * @param createTime the value for crf.create_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.create_user_id
     *
     * @return the value of crf.create_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.create_user_id
     *
     * @param createUserId the value for crf.create_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.update_time
     *
     * @return the value of crf.update_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.update_time
     *
     * @param updateTime the value for crf.update_time
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.update_user_id
     *
     * @return the value of crf.update_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.update_user_id
     *
     * @param updateUserId the value for crf.update_user_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crf.fk_tenant_id
     *
     * @return the value of crf.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crf.fk_tenant_id
     *
     * @param fkTenantId the value for crf.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 10:30:11 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }
}