package com.xtt.common.dao.model;

import java.util.Date;

public class PathologicDiagnosisResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkPatientDiagnosisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.fk_dialysis_campaign_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkDialysisCampaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.has_renal_biopsy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hasRenalBiopsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String sgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.other_sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String otherSgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String pgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.other_pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String otherPgn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String hereditaryNephropathy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String otherHereditaryNephropathy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String tin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.other_tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String otherTin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.has_nsp
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hasNsp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.has_tkd
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hasTkd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.other_reason
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String otherReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean isDraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.version
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pathologic_diagnosis_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.id
     *
     * @return the value of pathologic_diagnosis_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.id
     *
     * @param id the value for pathologic_diagnosis_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.fk_patient_diagnosis_id
     *
     * @return the value of pathologic_diagnosis_result.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkPatientDiagnosisId() {
        return fkPatientDiagnosisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.fk_patient_diagnosis_id
     *
     * @param fkPatientDiagnosisId the value for pathologic_diagnosis_result.fk_patient_diagnosis_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkPatientDiagnosisId(Long fkPatientDiagnosisId) {
        this.fkPatientDiagnosisId = fkPatientDiagnosisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.fk_dialysis_campaign_id
     *
     * @return the value of pathologic_diagnosis_result.fk_dialysis_campaign_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkDialysisCampaignId() {
        return fkDialysisCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.fk_dialysis_campaign_id
     *
     * @param fkDialysisCampaignId the value for pathologic_diagnosis_result.fk_dialysis_campaign_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkDialysisCampaignId(Long fkDialysisCampaignId) {
        this.fkDialysisCampaignId = fkDialysisCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.fk_patient_id
     *
     * @return the value of pathologic_diagnosis_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkPatientId() {
        return fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.fk_patient_id
     *
     * @param fkPatientId the value for pathologic_diagnosis_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkPatientId(Long fkPatientId) {
        this.fkPatientId = fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.has_renal_biopsy
     *
     * @return the value of pathologic_diagnosis_result.has_renal_biopsy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHasRenalBiopsy() {
        return hasRenalBiopsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.has_renal_biopsy
     *
     * @param hasRenalBiopsy the value for pathologic_diagnosis_result.has_renal_biopsy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHasRenalBiopsy(Boolean hasRenalBiopsy) {
        this.hasRenalBiopsy = hasRenalBiopsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.sgn
     *
     * @return the value of pathologic_diagnosis_result.sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getSgn() {
        return sgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.sgn
     *
     * @param sgn the value for pathologic_diagnosis_result.sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setSgn(String sgn) {
        this.sgn = sgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.other_sgn
     *
     * @return the value of pathologic_diagnosis_result.other_sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getOtherSgn() {
        return otherSgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.other_sgn
     *
     * @param otherSgn the value for pathologic_diagnosis_result.other_sgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOtherSgn(String otherSgn) {
        this.otherSgn = otherSgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.pgn
     *
     * @return the value of pathologic_diagnosis_result.pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getPgn() {
        return pgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.pgn
     *
     * @param pgn the value for pathologic_diagnosis_result.pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setPgn(String pgn) {
        this.pgn = pgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.other_pgn
     *
     * @return the value of pathologic_diagnosis_result.other_pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getOtherPgn() {
        return otherPgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.other_pgn
     *
     * @param otherPgn the value for pathologic_diagnosis_result.other_pgn
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOtherPgn(String otherPgn) {
        this.otherPgn = otherPgn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.hereditary_nephropathy
     *
     * @return the value of pathologic_diagnosis_result.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getHereditaryNephropathy() {
        return hereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.hereditary_nephropathy
     *
     * @param hereditaryNephropathy the value for pathologic_diagnosis_result.hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHereditaryNephropathy(String hereditaryNephropathy) {
        this.hereditaryNephropathy = hereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.other_hereditary_nephropathy
     *
     * @return the value of pathologic_diagnosis_result.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getOtherHereditaryNephropathy() {
        return otherHereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.other_hereditary_nephropathy
     *
     * @param otherHereditaryNephropathy the value for pathologic_diagnosis_result.other_hereditary_nephropathy
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOtherHereditaryNephropathy(String otherHereditaryNephropathy) {
        this.otherHereditaryNephropathy = otherHereditaryNephropathy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.tin
     *
     * @return the value of pathologic_diagnosis_result.tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getTin() {
        return tin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.tin
     *
     * @param tin the value for pathologic_diagnosis_result.tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setTin(String tin) {
        this.tin = tin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.other_tin
     *
     * @return the value of pathologic_diagnosis_result.other_tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getOtherTin() {
        return otherTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.other_tin
     *
     * @param otherTin the value for pathologic_diagnosis_result.other_tin
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOtherTin(String otherTin) {
        this.otherTin = otherTin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.has_nsp
     *
     * @return the value of pathologic_diagnosis_result.has_nsp
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHasNsp() {
        return hasNsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.has_nsp
     *
     * @param hasNsp the value for pathologic_diagnosis_result.has_nsp
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHasNsp(Boolean hasNsp) {
        this.hasNsp = hasNsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.has_tkd
     *
     * @return the value of pathologic_diagnosis_result.has_tkd
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHasTkd() {
        return hasTkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.has_tkd
     *
     * @param hasTkd the value for pathologic_diagnosis_result.has_tkd
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHasTkd(Boolean hasTkd) {
        this.hasTkd = hasTkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.other_reason
     *
     * @return the value of pathologic_diagnosis_result.other_reason
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getOtherReason() {
        return otherReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.other_reason
     *
     * @param otherReason the value for pathologic_diagnosis_result.other_reason
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOtherReason(String otherReason) {
        this.otherReason = otherReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.is_draft
     *
     * @return the value of pathologic_diagnosis_result.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getIsDraft() {
        return isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.is_draft
     *
     * @param isDraft the value for pathologic_diagnosis_result.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.operator_id
     *
     * @return the value of pathologic_diagnosis_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.operator_id
     *
     * @param operatorId the value for pathologic_diagnosis_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.version
     *
     * @return the value of pathologic_diagnosis_result.version
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.version
     *
     * @param version the value for pathologic_diagnosis_result.version
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.is_enable
     *
     * @return the value of pathologic_diagnosis_result.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.is_enable
     *
     * @param isEnable the value for pathologic_diagnosis_result.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.create_time
     *
     * @return the value of pathologic_diagnosis_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.create_time
     *
     * @param createTime the value for pathologic_diagnosis_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.create_user_id
     *
     * @return the value of pathologic_diagnosis_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.create_user_id
     *
     * @param createUserId the value for pathologic_diagnosis_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.update_time
     *
     * @return the value of pathologic_diagnosis_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.update_time
     *
     * @param updateTime the value for pathologic_diagnosis_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.update_user_id
     *
     * @return the value of pathologic_diagnosis_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.update_user_id
     *
     * @param updateUserId the value for pathologic_diagnosis_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pathologic_diagnosis_result.fk_tenant_id
     *
     * @return the value of pathologic_diagnosis_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pathologic_diagnosis_result.fk_tenant_id
     *
     * @param fkTenantId the value for pathologic_diagnosis_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }
}