package com.xtt.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

import com.xtt.platform.framework.core.model.MyBatisSuperModel;

public class Patient extends MyBatisSuperModel {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.account
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String account;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.name
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.initial
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String initial;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.password
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.id_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String idNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.sex
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.birthday
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.image_path
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String imagePath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.work_unit
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String workUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.profession
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String profession;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.emergency_mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String emergencyMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.province
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Integer province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.county
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Integer county;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.address
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.dry_weight
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private BigDecimal dryWeight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.balance
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private BigDecimal balance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.del_flag
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Boolean delFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Integer fkTenantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Long createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Long updateUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.medicare_card
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String medicareCard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.medicare_card_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String medicareCardType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.admission_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String admissionNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.spell_initials
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String spellInitials;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.outpatient_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String outpatientNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.id_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String idType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.emergency_contacts
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String emergencyContacts;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.emergency_mobile2
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String emergencyMobile2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.emergency_mobile3
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private String emergencyMobile3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.offset
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private BigDecimal offset;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.is_temp
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Boolean isTemp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column patient.dialysis_times
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	private Integer dialysisTimes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.id
	 *
	 * @return the value of patient.id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.id
	 *
	 * @param id
	 *            the value for patient.id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.account
	 *
	 * @return the value of patient.account
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.account
	 *
	 * @param account
	 *            the value for patient.account
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.name
	 *
	 * @return the value of patient.name
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.name
	 *
	 * @param name
	 *            the value for patient.name
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.initial
	 *
	 * @return the value of patient.initial
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getInitial() {
		return initial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.initial
	 *
	 * @param initial
	 *            the value for patient.initial
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setInitial(String initial) {
		this.initial = initial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.password
	 *
	 * @return the value of patient.password
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.password
	 *
	 * @param password
	 *            the value for patient.password
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.id_number
	 *
	 * @return the value of patient.id_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.id_number
	 *
	 * @param idNumber
	 *            the value for patient.id_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.sex
	 *
	 * @return the value of patient.sex
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.sex
	 *
	 * @param sex
	 *            the value for patient.sex
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.birthday
	 *
	 * @return the value of patient.birthday
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.birthday
	 *
	 * @param birthday
	 *            the value for patient.birthday
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.image_path
	 *
	 * @return the value of patient.image_path
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getImagePath() {
		return imagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.image_path
	 *
	 * @param imagePath
	 *            the value for patient.image_path
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.work_unit
	 *
	 * @return the value of patient.work_unit
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getWorkUnit() {
		return workUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.work_unit
	 *
	 * @param workUnit
	 *            the value for patient.work_unit
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.profession
	 *
	 * @return the value of patient.profession
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getProfession() {
		return profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.profession
	 *
	 * @param profession
	 *            the value for patient.profession
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setProfession(String profession) {
		this.profession = profession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.mobile
	 *
	 * @return the value of patient.mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.mobile
	 *
	 * @param mobile
	 *            the value for patient.mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.emergency_mobile
	 *
	 * @return the value of patient.emergency_mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getEmergencyMobile() {
		return emergencyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.emergency_mobile
	 *
	 * @param emergencyMobile
	 *            the value for patient.emergency_mobile
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setEmergencyMobile(String emergencyMobile) {
		this.emergencyMobile = emergencyMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.province
	 *
	 * @return the value of patient.province
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Integer getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.province
	 *
	 * @param province
	 *            the value for patient.province
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setProvince(Integer province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.county
	 *
	 * @return the value of patient.county
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Integer getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.county
	 *
	 * @param county
	 *            the value for patient.county
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setCounty(Integer county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.address
	 *
	 * @return the value of patient.address
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.address
	 *
	 * @param address
	 *            the value for patient.address
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.dry_weight
	 *
	 * @return the value of patient.dry_weight
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public BigDecimal getDryWeight() {
		return dryWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.dry_weight
	 *
	 * @param dryWeight
	 *            the value for patient.dry_weight
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setDryWeight(BigDecimal dryWeight) {
		this.dryWeight = dryWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.balance
	 *
	 * @return the value of patient.balance
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.balance
	 *
	 * @param balance
	 *            the value for patient.balance
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.del_flag
	 *
	 * @return the value of patient.del_flag
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.del_flag
	 *
	 * @param delFlag
	 *            the value for patient.del_flag
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.fk_tenant_id
	 *
	 * @return the value of patient.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Integer getFkTenantId() {
		return fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.fk_tenant_id
	 *
	 * @param fkTenantId
	 *            the value for patient.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setFkTenantId(Integer fkTenantId) {
		this.fkTenantId = fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.create_time
	 *
	 * @return the value of patient.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.create_time
	 *
	 * @param createTime
	 *            the value for patient.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.create_user_id
	 *
	 * @return the value of patient.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.create_user_id
	 *
	 * @param createUserId
	 *            the value for patient.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.update_time
	 *
	 * @return the value of patient.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.update_time
	 *
	 * @param updateTime
	 *            the value for patient.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.update_user_id
	 *
	 * @return the value of patient.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Long getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.update_user_id
	 *
	 * @param updateUserId
	 *            the value for patient.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.medicare_card
	 *
	 * @return the value of patient.medicare_card
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getMedicareCard() {
		return medicareCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.medicare_card
	 *
	 * @param medicareCard
	 *            the value for patient.medicare_card
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setMedicareCard(String medicareCard) {
		this.medicareCard = medicareCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.medicare_card_type
	 *
	 * @return the value of patient.medicare_card_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getMedicareCardType() {
		return medicareCardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.medicare_card_type
	 *
	 * @param medicareCardType
	 *            the value for patient.medicare_card_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setMedicareCardType(String medicareCardType) {
		this.medicareCardType = medicareCardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.admission_number
	 *
	 * @return the value of patient.admission_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getAdmissionNumber() {
		return admissionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.admission_number
	 *
	 * @param admissionNumber
	 *            the value for patient.admission_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setAdmissionNumber(String admissionNumber) {
		this.admissionNumber = admissionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.spell_initials
	 *
	 * @return the value of patient.spell_initials
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getSpellInitials() {
		return spellInitials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.spell_initials
	 *
	 * @param spellInitials
	 *            the value for patient.spell_initials
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setSpellInitials(String spellInitials) {
		this.spellInitials = spellInitials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.outpatient_number
	 *
	 * @return the value of patient.outpatient_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getOutpatientNumber() {
		return outpatientNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.outpatient_number
	 *
	 * @param outpatientNumber
	 *            the value for patient.outpatient_number
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setOutpatientNumber(String outpatientNumber) {
		this.outpatientNumber = outpatientNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.id_type
	 *
	 * @return the value of patient.id_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.id_type
	 *
	 * @param idType
	 *            the value for patient.id_type
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setIdType(String idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.emergency_contacts
	 *
	 * @return the value of patient.emergency_contacts
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getEmergencyContacts() {
		return emergencyContacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.emergency_contacts
	 *
	 * @param emergencyContacts
	 *            the value for patient.emergency_contacts
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setEmergencyContacts(String emergencyContacts) {
		this.emergencyContacts = emergencyContacts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.emergency_mobile2
	 *
	 * @return the value of patient.emergency_mobile2
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getEmergencyMobile2() {
		return emergencyMobile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.emergency_mobile2
	 *
	 * @param emergencyMobile2
	 *            the value for patient.emergency_mobile2
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setEmergencyMobile2(String emergencyMobile2) {
		this.emergencyMobile2 = emergencyMobile2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.emergency_mobile3
	 *
	 * @return the value of patient.emergency_mobile3
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public String getEmergencyMobile3() {
		return emergencyMobile3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.emergency_mobile3
	 *
	 * @param emergencyMobile3
	 *            the value for patient.emergency_mobile3
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setEmergencyMobile3(String emergencyMobile3) {
		this.emergencyMobile3 = emergencyMobile3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.offset
	 *
	 * @return the value of patient.offset
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public BigDecimal getOffset() {
		return offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.offset
	 *
	 * @param offset
	 *            the value for patient.offset
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setOffset(BigDecimal offset) {
		this.offset = offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.is_temp
	 *
	 * @return the value of patient.is_temp
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Boolean getIsTemp() {
		return isTemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.is_temp
	 *
	 * @param isTemp
	 *            the value for patient.is_temp
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setIsTemp(Boolean isTemp) {
		this.isTemp = isTemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column patient.dialysis_times
	 *
	 * @return the value of patient.dialysis_times
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public Integer getDialysisTimes() {
		return dialysisTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column patient.dialysis_times
	 *
	 * @param dialysisTimes
	 *            the value for patient.dialysis_times
	 *
	 * @mbggenerated Fri Jun 17 09:55:17 CST 2016
	 */
	public void setDialysisTimes(Integer dialysisTimes) {
		this.dialysisTimes = dialysisTimes;
	}
}