package com.xtt.common.dao.model;

import java.util.Date;

public class PatientAssayMonthRScope {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.assay_class
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private String assayClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.month_value
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Integer monthValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.fk_tenant_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.start_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.end_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.create_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.create_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.update_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_month_r_scope.update_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.id
     *
     * @return the value of patient_assay_month_r_scope.id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.id
     *
     * @param id the value for patient_assay_month_r_scope.id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.assay_class
     *
     * @return the value of patient_assay_month_r_scope.assay_class
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public String getAssayClass() {
        return assayClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.assay_class
     *
     * @param assayClass the value for patient_assay_month_r_scope.assay_class
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setAssayClass(String assayClass) {
        this.assayClass = assayClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.month_value
     *
     * @return the value of patient_assay_month_r_scope.month_value
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Integer getMonthValue() {
        return monthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.month_value
     *
     * @param monthValue the value for patient_assay_month_r_scope.month_value
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setMonthValue(Integer monthValue) {
        this.monthValue = monthValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.fk_tenant_id
     *
     * @return the value of patient_assay_month_r_scope.fk_tenant_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.fk_tenant_id
     *
     * @param fkTenantId the value for patient_assay_month_r_scope.fk_tenant_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.start_time
     *
     * @return the value of patient_assay_month_r_scope.start_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.start_time
     *
     * @param startTime the value for patient_assay_month_r_scope.start_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.end_time
     *
     * @return the value of patient_assay_month_r_scope.end_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.end_time
     *
     * @param endTime the value for patient_assay_month_r_scope.end_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.create_time
     *
     * @return the value of patient_assay_month_r_scope.create_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.create_time
     *
     * @param createTime the value for patient_assay_month_r_scope.create_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.create_user_id
     *
     * @return the value of patient_assay_month_r_scope.create_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.create_user_id
     *
     * @param createUserId the value for patient_assay_month_r_scope.create_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.update_time
     *
     * @return the value of patient_assay_month_r_scope.update_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.update_time
     *
     * @param updateTime the value for patient_assay_month_r_scope.update_time
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_month_r_scope.update_user_id
     *
     * @return the value of patient_assay_month_r_scope.update_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_month_r_scope.update_user_id
     *
     * @param updateUserId the value for patient_assay_month_r_scope.update_user_id
     *
     * @mbggenerated Mon Jul 04 11:04:44 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}