package com.xtt.common.dao.model;

import java.util.Date;

public class PatientCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.fk_pt_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkPtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.card_type
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.card_no
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.del_flag
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_card.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.id
     *
     * @return the value of patient_card.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.id
     *
     * @param id the value for patient_card.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.fk_pt_id
     *
     * @return the value of patient_card.fk_pt_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkPtId() {
        return fkPtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.fk_pt_id
     *
     * @param fkPtId the value for patient_card.fk_pt_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkPtId(Long fkPtId) {
        this.fkPtId = fkPtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.card_type
     *
     * @return the value of patient_card.card_type
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.card_type
     *
     * @param cardType the value for patient_card.card_type
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.card_no
     *
     * @return the value of patient_card.card_no
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.card_no
     *
     * @param cardNo the value for patient_card.card_no
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.del_flag
     *
     * @return the value of patient_card.del_flag
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.del_flag
     *
     * @param delFlag the value for patient_card.del_flag
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.fk_tenant_id
     *
     * @return the value of patient_card.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.fk_tenant_id
     *
     * @param fkTenantId the value for patient_card.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.create_time
     *
     * @return the value of patient_card.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.create_time
     *
     * @param createTime the value for patient_card.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.create_user_id
     *
     * @return the value of patient_card.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.create_user_id
     *
     * @param createUserId the value for patient_card.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.update_time
     *
     * @return the value of patient_card.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.update_time
     *
     * @param updateTime the value for patient_card.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_card.update_user_id
     *
     * @return the value of patient_card.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_card.update_user_id
     *
     * @param updateUserId the value for patient_card.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}