package com.xtt.common.dao.model;

import java.util.Date;

public class PatientDiagnosis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.last_step
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer lastStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean isDraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_diagnosis.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.id
     *
     * @return the value of patient_diagnosis.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.id
     *
     * @param id the value for patient_diagnosis.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.fk_patient_id
     *
     * @return the value of patient_diagnosis.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkPatientId() {
        return fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.fk_patient_id
     *
     * @param fkPatientId the value for patient_diagnosis.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkPatientId(Long fkPatientId) {
        this.fkPatientId = fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.last_step
     *
     * @return the value of patient_diagnosis.last_step
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getLastStep() {
        return lastStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.last_step
     *
     * @param lastStep the value for patient_diagnosis.last_step
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setLastStep(Integer lastStep) {
        this.lastStep = lastStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.is_draft
     *
     * @return the value of patient_diagnosis.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getIsDraft() {
        return isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.is_draft
     *
     * @param isDraft the value for patient_diagnosis.is_draft
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.operator_id
     *
     * @return the value of patient_diagnosis.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.operator_id
     *
     * @param operatorId the value for patient_diagnosis.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.fk_tenant_id
     *
     * @return the value of patient_diagnosis.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.fk_tenant_id
     *
     * @param fkTenantId the value for patient_diagnosis.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.create_time
     *
     * @return the value of patient_diagnosis.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.create_time
     *
     * @param createTime the value for patient_diagnosis.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.create_user_id
     *
     * @return the value of patient_diagnosis.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.create_user_id
     *
     * @param createUserId the value for patient_diagnosis.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.update_time
     *
     * @return the value of patient_diagnosis.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.update_time
     *
     * @param updateTime the value for patient_diagnosis.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_diagnosis.update_user_id
     *
     * @return the value of patient_diagnosis.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_diagnosis.update_user_id
     *
     * @param updateUserId the value for patient_diagnosis.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}