package com.xtt.common.dao.model;

import java.util.Date;

public class PatientAssayResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long fkPatientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hav
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hbv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hbv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hcv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hcv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hev
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hiv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hiv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.hsv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean hsv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.is_enabled
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean isEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.id
     *
     * @return the value of patient_assay_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.id
     *
     * @param id the value for patient_assay_result.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.fk_patient_id
     *
     * @return the value of patient_assay_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getFkPatientId() {
        return fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.fk_patient_id
     *
     * @param fkPatientId the value for patient_assay_result.fk_patient_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkPatientId(Long fkPatientId) {
        this.fkPatientId = fkPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hav
     *
     * @return the value of patient_assay_result.hav
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHav() {
        return hav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hav
     *
     * @param hav the value for patient_assay_result.hav
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHav(Boolean hav) {
        this.hav = hav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hbv
     *
     * @return the value of patient_assay_result.hbv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHbv() {
        return hbv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hbv
     *
     * @param hbv the value for patient_assay_result.hbv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHbv(Boolean hbv) {
        this.hbv = hbv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hcv
     *
     * @return the value of patient_assay_result.hcv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHcv() {
        return hcv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hcv
     *
     * @param hcv the value for patient_assay_result.hcv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHcv(Boolean hcv) {
        this.hcv = hcv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hev
     *
     * @return the value of patient_assay_result.hev
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHev() {
        return hev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hev
     *
     * @param hev the value for patient_assay_result.hev
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHev(Boolean hev) {
        this.hev = hev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hiv
     *
     * @return the value of patient_assay_result.hiv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHiv() {
        return hiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hiv
     *
     * @param hiv the value for patient_assay_result.hiv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHiv(Boolean hiv) {
        this.hiv = hiv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.hsv
     *
     * @return the value of patient_assay_result.hsv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getHsv() {
        return hsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.hsv
     *
     * @param hsv the value for patient_assay_result.hsv
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setHsv(Boolean hsv) {
        this.hsv = hsv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.operator_id
     *
     * @return the value of patient_assay_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.operator_id
     *
     * @param operatorId the value for patient_assay_result.operator_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.is_enabled
     *
     * @return the value of patient_assay_result.is_enabled
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.is_enabled
     *
     * @param isEnabled the value for patient_assay_result.is_enabled
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.fk_tenant_id
     *
     * @return the value of patient_assay_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.fk_tenant_id
     *
     * @param fkTenantId the value for patient_assay_result.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.create_time
     *
     * @return the value of patient_assay_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.create_time
     *
     * @param createTime the value for patient_assay_result.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.create_user_id
     *
     * @return the value of patient_assay_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.create_user_id
     *
     * @param createUserId the value for patient_assay_result.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.update_time
     *
     * @return the value of patient_assay_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.update_time
     *
     * @param updateTime the value for patient_assay_result.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_result.update_user_id
     *
     * @return the value of patient_assay_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_result.update_user_id
     *
     * @param updateUserId the value for patient_assay_result.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}