package com.xtt.common.dao.model;

import java.util.Date;

public class PatientAssayConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.end_date
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.fk_tenant_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.create_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.create_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.update_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_conf.update_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.id
     *
     * @return the value of patient_assay_conf.id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.id
     *
     * @param id the value for patient_assay_conf.id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.end_date
     *
     * @return the value of patient_assay_conf.end_date
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.end_date
     *
     * @param endDate the value for patient_assay_conf.end_date
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.fk_tenant_id
     *
     * @return the value of patient_assay_conf.fk_tenant_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.fk_tenant_id
     *
     * @param fkTenantId the value for patient_assay_conf.fk_tenant_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.create_time
     *
     * @return the value of patient_assay_conf.create_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.create_time
     *
     * @param createTime the value for patient_assay_conf.create_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.create_user_id
     *
     * @return the value of patient_assay_conf.create_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.create_user_id
     *
     * @param createUserId the value for patient_assay_conf.create_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.update_time
     *
     * @return the value of patient_assay_conf.update_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.update_time
     *
     * @param updateTime the value for patient_assay_conf.update_time
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_conf.update_user_id
     *
     * @return the value of patient_assay_conf.update_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_conf.update_user_id
     *
     * @param updateUserId the value for patient_assay_conf.update_user_id
     *
     * @mbggenerated Thu Jul 14 14:41:28 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}