package com.xtt.common.dao.model;

import java.util.Date;

public class PatientAssayFilterRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.rule_code
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String ruleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.rule_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Boolean isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.min_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String minValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.max_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String maxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.function_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_assay_filter_rule.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.id
     *
     * @return the value of patient_assay_filter_rule.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.id
     *
     * @param id the value for patient_assay_filter_rule.id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.rule_code
     *
     * @return the value of patient_assay_filter_rule.rule_code
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getRuleCode() {
        return ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.rule_code
     *
     * @param ruleCode the value for patient_assay_filter_rule.rule_code
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.rule_name
     *
     * @return the value of patient_assay_filter_rule.rule_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.rule_name
     *
     * @param ruleName the value for patient_assay_filter_rule.rule_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.is_enable
     *
     * @return the value of patient_assay_filter_rule.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.is_enable
     *
     * @param isEnable the value for patient_assay_filter_rule.is_enable
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.min_value
     *
     * @return the value of patient_assay_filter_rule.min_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.min_value
     *
     * @param minValue the value for patient_assay_filter_rule.min_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.max_value
     *
     * @return the value of patient_assay_filter_rule.max_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.max_value
     *
     * @param maxValue the value for patient_assay_filter_rule.max_value
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.function_name
     *
     * @return the value of patient_assay_filter_rule.function_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.function_name
     *
     * @param functionName the value for patient_assay_filter_rule.function_name
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.fk_tenant_id
     *
     * @return the value of patient_assay_filter_rule.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.fk_tenant_id
     *
     * @param fkTenantId the value for patient_assay_filter_rule.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.create_time
     *
     * @return the value of patient_assay_filter_rule.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.create_time
     *
     * @param createTime the value for patient_assay_filter_rule.create_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.create_user_id
     *
     * @return the value of patient_assay_filter_rule.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.create_user_id
     *
     * @param createUserId the value for patient_assay_filter_rule.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.update_time
     *
     * @return the value of patient_assay_filter_rule.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.update_time
     *
     * @param updateTime the value for patient_assay_filter_rule.update_time
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_assay_filter_rule.update_user_id
     *
     * @return the value of patient_assay_filter_rule.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_assay_filter_rule.update_user_id
     *
     * @param updateUserId the value for patient_assay_filter_rule.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:55:17 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}