package com.xtt.common.dao.model;

import java.util.Date;

public class SysDbSource {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_key
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbKey;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_key_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbKeyDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_driverClassName
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbDriverclassname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_url
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_username
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbUsername;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_pwd
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbPwd;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_version
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbVersion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_sql_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbSqlDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_key_p
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbKeyP;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Integer fkTenantId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.del_flag
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.create_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.update_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private Long updateUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_db_source.db_sql
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    private String dbSql;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.id
     *
     * @return the value of sys_db_source.id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.id
     *
     * @param id
     *            the value for sys_db_source.id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_key
     *
     * @return the value of sys_db_source.db_key
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbKey() {
        return dbKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_key
     *
     * @param dbKey
     *            the value for sys_db_source.db_key
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbKey(String dbKey) {
        this.dbKey = dbKey;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_key_desc
     *
     * @return the value of sys_db_source.db_key_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbKeyDesc() {
        return dbKeyDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_key_desc
     *
     * @param dbKeyDesc
     *            the value for sys_db_source.db_key_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbKeyDesc(String dbKeyDesc) {
        this.dbKeyDesc = dbKeyDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_driverClassName
     *
     * @return the value of sys_db_source.db_driverClassName
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbDriverclassname() {
        return dbDriverclassname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_driverClassName
     *
     * @param dbDriverclassname
     *            the value for sys_db_source.db_driverClassName
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbDriverclassname(String dbDriverclassname) {
        this.dbDriverclassname = dbDriverclassname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_url
     *
     * @return the value of sys_db_source.db_url
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbUrl() {
        return dbUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_url
     *
     * @param dbUrl
     *            the value for sys_db_source.db_url
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbUrl(String dbUrl) {
        this.dbUrl = dbUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_username
     *
     * @return the value of sys_db_source.db_username
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbUsername() {
        return dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_username
     *
     * @param dbUsername
     *            the value for sys_db_source.db_username
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbUsername(String dbUsername) {
        this.dbUsername = dbUsername;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_pwd
     *
     * @return the value of sys_db_source.db_pwd
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbPwd() {
        return dbPwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_pwd
     *
     * @param dbPwd
     *            the value for sys_db_source.db_pwd
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbPwd(String dbPwd) {
        this.dbPwd = dbPwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_version
     *
     * @return the value of sys_db_source.db_version
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbVersion() {
        return dbVersion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_version
     *
     * @param dbVersion
     *            the value for sys_db_source.db_version
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbVersion(String dbVersion) {
        this.dbVersion = dbVersion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_sql_desc
     *
     * @return the value of sys_db_source.db_sql_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbSqlDesc() {
        return dbSqlDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_sql_desc
     *
     * @param dbSqlDesc
     *            the value for sys_db_source.db_sql_desc
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbSqlDesc(String dbSqlDesc) {
        this.dbSqlDesc = dbSqlDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_key_p
     *
     * @return the value of sys_db_source.db_key_p
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbKeyP() {
        return dbKeyP;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_key_p
     *
     * @param dbKeyP
     *            the value for sys_db_source.db_key_p
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbKeyP(String dbKeyP) {
        this.dbKeyP = dbKeyP;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.fk_tenant_id
     *
     * @return the value of sys_db_source.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Integer getFkTenantId() {
        return fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.fk_tenant_id
     *
     * @param fkTenantId
     *            the value for sys_db_source.fk_tenant_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setFkTenantId(Integer fkTenantId) {
        this.fkTenantId = fkTenantId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.del_flag
     *
     * @return the value of sys_db_source.del_flag
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.del_flag
     *
     * @param delFlag
     *            the value for sys_db_source.del_flag
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.create_time
     *
     * @return the value of sys_db_source.create_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.create_time
     *
     * @param createTime
     *            the value for sys_db_source.create_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.create_user_id
     *
     * @return the value of sys_db_source.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.create_user_id
     *
     * @param createUserId
     *            the value for sys_db_source.create_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.update_time
     *
     * @return the value of sys_db_source.update_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.update_time
     *
     * @param updateTime
     *            the value for sys_db_source.update_time
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.update_user_id
     *
     * @return the value of sys_db_source.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.update_user_id
     *
     * @param updateUserId
     *            the value for sys_db_source.update_user_id
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_db_source.db_sql
     *
     * @return the value of sys_db_source.db_sql
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public String getDbSql() {
        return dbSql;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_db_source.db_sql
     *
     * @param dbSql
     *            the value for sys_db_source.db_sql
     *
     * @mbggenerated Fri Jun 17 09:57:37 CST 2016
     */
    public void setDbSql(String dbSql) {
        this.dbSql = dbSql;
    }
}