package com.xtt.common.dao.model;

import java.util.Date;

public class SysParam {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.param_name
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private String paramName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.param_desc
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private String paramDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.param_value
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private String paramValue;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.dic_type
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private String dicType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.param_unit
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private String paramUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Integer fkTenantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Long createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_param.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	private Long updateUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.id
	 *
	 * @return the value of sys_param.id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.id
	 *
	 * @param id
	 *            the value for sys_param.id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.param_name
	 *
	 * @return the value of sys_param.param_name
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public String getParamName() {
		return paramName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.param_name
	 *
	 * @param paramName
	 *            the value for sys_param.param_name
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.param_desc
	 *
	 * @return the value of sys_param.param_desc
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public String getParamDesc() {
		return paramDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.param_desc
	 *
	 * @param paramDesc
	 *            the value for sys_param.param_desc
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.param_value
	 *
	 * @return the value of sys_param.param_value
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public String getParamValue() {
		return paramValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.param_value
	 *
	 * @param paramValue
	 *            the value for sys_param.param_value
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.dic_type
	 *
	 * @return the value of sys_param.dic_type
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public String getDicType() {
		return dicType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.dic_type
	 *
	 * @param dicType
	 *            the value for sys_param.dic_type
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setDicType(String dicType) {
		this.dicType = dicType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.param_unit
	 *
	 * @return the value of sys_param.param_unit
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public String getParamUnit() {
		return paramUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.param_unit
	 *
	 * @param paramUnit
	 *            the value for sys_param.param_unit
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setParamUnit(String paramUnit) {
		this.paramUnit = paramUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.fk_tenant_id
	 *
	 * @return the value of sys_param.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Integer getFkTenantId() {
		return fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.fk_tenant_id
	 *
	 * @param fkTenantId
	 *            the value for sys_param.fk_tenant_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setFkTenantId(Integer fkTenantId) {
		this.fkTenantId = fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.create_time
	 *
	 * @return the value of sys_param.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.create_time
	 *
	 * @param createTime
	 *            the value for sys_param.create_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.create_user_id
	 *
	 * @return the value of sys_param.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.create_user_id
	 *
	 * @param createUserId
	 *            the value for sys_param.create_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.update_time
	 *
	 * @return the value of sys_param.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.update_time
	 *
	 * @param updateTime
	 *            the value for sys_param.update_time
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_param.update_user_id
	 *
	 * @return the value of sys_param.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public Long getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_param.update_user_id
	 *
	 * @param updateUserId
	 *            the value for sys_param.update_user_id
	 *
	 * @mbggenerated Fri Jun 17 09:57:37 CST 2016
	 */
	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}
}