package com.xtt.common.dao.model;

import java.util.Date;

public class SysTenant {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.name
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.is_enable
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Boolean isEnable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.start_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Date startDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.end_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Date endDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.create_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.create_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Long createUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.update_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_tenant.update_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	private Long updateUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.id
	 *
	 * @return the value of sys_tenant.id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.id
	 *
	 * @param id
	 *            the value for sys_tenant.id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.name
	 *
	 * @return the value of sys_tenant.name
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.name
	 *
	 * @param name
	 *            the value for sys_tenant.name
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.is_enable
	 *
	 * @return the value of sys_tenant.is_enable
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Boolean getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.is_enable
	 *
	 * @param isEnable
	 *            the value for sys_tenant.is_enable
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setIsEnable(Boolean isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.start_date
	 *
	 * @return the value of sys_tenant.start_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.start_date
	 *
	 * @param startDate
	 *            the value for sys_tenant.start_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.end_date
	 *
	 * @return the value of sys_tenant.end_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.end_date
	 *
	 * @param endDate
	 *            the value for sys_tenant.end_date
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.create_time
	 *
	 * @return the value of sys_tenant.create_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.create_time
	 *
	 * @param createTime
	 *            the value for sys_tenant.create_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.create_user_id
	 *
	 * @return the value of sys_tenant.create_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.create_user_id
	 *
	 * @param createUserId
	 *            the value for sys_tenant.create_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.update_time
	 *
	 * @return the value of sys_tenant.update_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.update_time
	 *
	 * @param updateTime
	 *            the value for sys_tenant.update_time
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_tenant.update_user_id
	 *
	 * @return the value of sys_tenant.update_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public Long getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_tenant.update_user_id
	 *
	 * @param updateUserId
	 *            the value for sys_tenant.update_user_id
	 *
	 * @mbggenerated Thu Mar 03 13:46:30 CST 2016
	 */
	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}
}