package com.xtt.common.dao.model;

import java.util.Date;

public class SysUser2obj {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.fk_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Long fkUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.fk_obj_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Long fkObjId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.create_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.create_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.update_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user2obj.update_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    private Long updateUserId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.fk_user_id
     *
     * @return the value of sys_user2obj.fk_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Long getFkUserId() {
        return fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.fk_user_id
     *
     * @param fkUserId
     *            the value for sys_user2obj.fk_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setFkUserId(Long fkUserId) {
        this.fkUserId = fkUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.fk_obj_id
     *
     * @return the value of sys_user2obj.fk_obj_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Long getFkObjId() {
        return fkObjId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.fk_obj_id
     *
     * @param fkObjId
     *            the value for sys_user2obj.fk_obj_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setFkObjId(Long fkObjId) {
        this.fkObjId = fkObjId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.create_time
     *
     * @return the value of sys_user2obj.create_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.create_time
     *
     * @param createTime
     *            the value for sys_user2obj.create_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.create_user_id
     *
     * @return the value of sys_user2obj.create_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.create_user_id
     *
     * @param createUserId
     *            the value for sys_user2obj.create_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.update_time
     *
     * @return the value of sys_user2obj.update_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.update_time
     *
     * @param updateTime
     *            the value for sys_user2obj.update_time
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user2obj.update_user_id
     *
     * @return the value of sys_user2obj.update_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public Long getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user2obj.update_user_id
     *
     * @param updateUserId
     *            the value for sys_user2obj.update_user_id
     *
     * @mbggenerated Tue Sep 08 13:30:46 CST 2015
     */
    public void setUpdateUserId(Long updateUserId) {
        this.updateUserId = updateUserId;
    }
}