package com.xtt.common.dao.model;

import java.util.Date;

public class SysUser {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.account
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String account;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.name
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.initial
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String initial;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.image_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String imagePath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.autograph_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String autographPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.sex
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String sex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.birthday
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Date birthday;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.position
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String position;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.mobile
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String mobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.sub_phone
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String subPhone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.sys_owner
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String sysOwner;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.skin
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private String skin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.del_flag
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Boolean delFlag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.fk_tenant_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Integer fkTenantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.create_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Long createUserId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.update_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Date updateTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.update_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	private Long updateUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 *
	 * @return the value of sys_user.id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 *
	 * @param id
	 *            the value for sys_user.id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.account
	 *
	 * @return the value of sys_user.account
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.account
	 *
	 * @param account
	 *            the value for sys_user.account
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.name
	 *
	 * @return the value of sys_user.name
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.name
	 *
	 * @param name
	 *            the value for sys_user.name
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.initial
	 *
	 * @return the value of sys_user.initial
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getInitial() {
		return initial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.initial
	 *
	 * @param initial
	 *            the value for sys_user.initial
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setInitial(String initial) {
		this.initial = initial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 *
	 * @return the value of sys_user.password
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 *
	 * @param password
	 *            the value for sys_user.password
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.image_path
	 *
	 * @return the value of sys_user.image_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getImagePath() {
		return imagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.autograph_path
	 *
	 * @param autographPath
	 *            the value for sys_user.autograph_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setAutographPath(String autographPath) {
		this.autographPath = autographPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.autograph_path
	 *
	 * @return the value of sys_user.autograph_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getAutographPath() {
		return autographPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.image_path
	 *
	 * @param imagePath
	 *            the value for sys_user.image_path
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.sex
	 *
	 * @return the value of sys_user.sex
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.sex
	 *
	 * @param sex
	 *            the value for sys_user.sex
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.birthday
	 *
	 * @return the value of sys_user.birthday
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.birthday
	 *
	 * @param birthday
	 *            the value for sys_user.birthday
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.position
	 *
	 * @return the value of sys_user.position
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.position
	 *
	 * @param position
	 *            the value for sys_user.position
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.mobile
	 *
	 * @return the value of sys_user.mobile
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.mobile
	 *
	 * @param mobile
	 *            the value for sys_user.mobile
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.sub_phone
	 *
	 * @return the value of sys_user.sub_phone
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getSubPhone() {
		return subPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.sub_phone
	 *
	 * @param subPhone
	 *            the value for sys_user.sub_phone
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setSubPhone(String subPhone) {
		this.subPhone = subPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.sys_owner
	 *
	 * @return the value of sys_user.sys_owner
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getSysOwner() {
		return sysOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.sys_owner
	 *
	 * @param sysOwner
	 *            the value for sys_user.sys_owner
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setSysOwner(String sysOwner) {
		this.sysOwner = sysOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.skin
	 *
	 * @return the value of sys_user.skin
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public String getSkin() {
		return skin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.skin
	 *
	 * @param sysOwner
	 *            the value for sys_user.skin
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setSkin(String skin) {
		this.skin = skin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.del_flag
	 *
	 * @return the value of sys_user.del_flag
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Boolean getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.del_flag
	 *
	 * @param delFlag
	 *            the value for sys_user.del_flag
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setDelFlag(Boolean delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.fk_tenant_id
	 *
	 * @return the value of sys_user.fk_tenant_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Integer getFkTenantId() {
		return fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.fk_tenant_id
	 *
	 * @param fkTenantId
	 *            the value for sys_user.fk_tenant_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setFkTenantId(Integer fkTenantId) {
		this.fkTenantId = fkTenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_time
	 *
	 * @return the value of sys_user.create_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_time
	 *
	 * @param createTime
	 *            the value for sys_user.create_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.create_user_id
	 *
	 * @return the value of sys_user.create_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Long getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.create_user_id
	 *
	 * @param createUserId
	 *            the value for sys_user.create_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setCreateUserId(Long createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.update_time
	 *
	 * @return the value of sys_user.update_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.update_time
	 *
	 * @param updateTime
	 *            the value for sys_user.update_time
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.update_user_id
	 *
	 * @return the value of sys_user.update_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public Long getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.update_user_id
	 *
	 * @param updateUserId
	 *            the value for sys_user.update_user_id
	 *
	 * @mbggenerated Mon Jun 27 14:47:56 CST 2016
	 */
	public void setUpdateUserId(Long updateUserId) {
		this.updateUserId = updateUserId;
	}
}
